trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'

pool:
  vmImage: $(imageName)

steps:
- script: |
    $(python2) --version
    $(python3) --version
    pip install mercurial
    hg clone https://foss.heptapod.net/octobus/mercurial-devel -r cfca4e64d577 -r 794874e83ec7 -r 0c7498610e47
    cd mercurial-devel

    hg up -C cfca4e64d577
    echo 'at cfca4e64d577:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

    hg up -C 794874e83ec7
    echo 'at 794874e83ec7:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

    hg up -C 0c7498610e47
    echo 'at 0c7498610e47:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
