trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
    mac:
      imageName: 'macOS-10.15'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- script: |
    hg clone https://foss.heptapod.net/octobus/mercurial-devel -r c00eb0fb6a5e -r a5e47701202a -r 0d2b5e331bc2
    cd mercurial-devel
    hg up -C c00eb0fb6a5e
    PYTHONPATH=. SILENT_BE_NOISY=1 python2 tests/test-stdio.py -v
    PYTHONPATH=. SILENT_BE_NOISY=1 python3 tests/test-stdio.py -v
    hg up -C a5e47701202a
    PYTHONPATH=. SILENT_BE_NOISY=1 python2 tests/test-stdio.py -v
    PYTHONPATH=. SILENT_BE_NOISY=1 python3 tests/test-stdio.py -v
    hg up -C 0d2b5e331bc2
    PYTHONPATH=. SILENT_BE_NOISY=1 python2 tests/test-stdio.py -v
    PYTHONPATH=. SILENT_BE_NOISY=1 python3 tests/test-stdio.py -v
