trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
    mac:
      imageName: 'macOS-10.15'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

jobs:
- job: clone
  steps:
  - script: hg clone https://foss.heptapod.net/octobus/mercurial-devel -r c00eb0fb6a5e -r a5e47701202a -r 0d2b5e331bc2
- job: c00eb0fb6a5e
  dependsOn: clone
  steps:
  - script: cd mercurial-devel
  - script: hg up c00eb0fb6a5e
  - script: PYTHONPATH=. SILENT_BE_NOISY=1 python2 tests/test-stdio.py -v
  - script: PYTHONPATH=. SILENT_BE_NOISY=1 python3 tests/test-stdio.py -v
- job: a5e47701202a
  dependsOn: clone
  steps:
  - script: cd mercurial-devel
  - script: hg up a5e47701202a
  - script: PYTHONPATH=. SILENT_BE_NOISY=1 python2 tests/test-stdio.py -v
  - script: PYTHONPATH=. SILENT_BE_NOISY=1 python3 tests/test-stdio.py -v
- job: 0d2b5e331bc2
  dependsOn: clone
  steps:
  - script: cd mercurial-devel
  - script: hg up 0d2b5e331bc2
  - script: PYTHONPATH=. SILENT_BE_NOISY=1 python2 tests/test-stdio.py -v
  - script: PYTHONPATH=. SILENT_BE_NOISY=1 python3 tests/test-stdio.py -v