trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /home/vsts/.cache/pip
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /Users/runner/Library/Caches/pip
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'
      pip_cache_dir: C:\Users\VssAdministrator\AppData\Local\pip\cache

pool:
  vmImage: $(imageName)

steps:
- script: $(python2) --version
- script: $(python3) --version
- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)"'
    path: $(pip_cache_dir)
- script: pip install wheel
- script: pip install mercurial
- task: Cache@2
  inputs:
    key: 'hg | "$(Agent.OS)"'
    path: mercurial-devel
- bash: |
    if [ ! -d "mercurial-devel" ]; then
        hg clone https://hg.sr.ht/~mjacob/hg-own -r 194c0bceb01e -r 4ad277267aac -r 818bd3ba0a81 -r 31bd3f6c75a8 -r d1ed96d04b1b || exit
    fi
    cd mercurial-devel
    hg pull https://hg.sr.ht/~mjacob/hg-own -r 194c0bceb01e -r 4ad277267aac -r 818bd3ba0a81 -r 31bd3f6c75a8 -r d1ed96d04b1b

- script: |
    echo 'update to 194c0bceb01e:'
    hg up -C 194c0bceb01e
  workingDirectory: mercurial-devel
  displayName: Update to 194c0bceb01e
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 4ad277267aac:'
    hg up -C 4ad277267aac
  workingDirectory: mercurial-devel
  displayName: Update to 4ad277267aac
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 818bd3ba0a81:'
    hg up -C 818bd3ba0a81
  workingDirectory: mercurial-devel
  displayName: Update to 818bd3ba0a81
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 31bd3f6c75a8:'
    hg up -C 31bd3f6c75a8
  workingDirectory: mercurial-devel
  displayName: Update to 31bd3f6c75a8
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to d1ed96d04b1b:'
    hg up -C d1ed96d04b1b
  workingDirectory: mercurial-devel
  displayName: Update to d1ed96d04b1b
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

