trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'

pool:
  vmImage: $(imageName)

steps:
- script: |
    $(python2) --version
    $(python3) --version
    pip install mercurial
    hg clone https://foss.heptapod.net/octobus/mercurial-devel -r 9acfe2ba8ec4 -r da7c48b286d3 -r 9ea93d547071
    cd mercurial-devel
    hg up -C 9acfe2ba8ec4
    $(python2) tests/test-stdio.py -v
    $(python3) tests/test-stdio.py -v
    hg up -C da7c48b286d3
    $(python2) tests/test-stdio.py -v
    $(python3) tests/test-stdio.py -v
    hg up -C 9ea93d547071
    $(python2) tests/test-stdio.py -v
    $(python3) tests/test-stdio.py -v
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
