trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /home/vsts/.cache/pip
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /Users/runner/Library/Caches/pip
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'
      pip_cache_dir: C:\Users\VssAdministrator\AppData\Local\pip\cache

pool:
  vmImage: $(imageName)

steps:
- script: $(python2) --version
- script: $(python3) --version
- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)"'
    path: $(pip_cache_dir)
- script: pip install wheel
- script: pip install mercurial
- task: Cache@2
  inputs:
    key: 'hg | "$(Agent.OS)"'
    path: mercurial-devel
- bash: |
    if [ ! -d "mercurial-devel" ]; then
        hg clone https://hg.sr.ht/~mjacob/hg-own -r 2fc7b6138a58 -r e7f9ada07e5f -r ca22543b6f9d -r 74825f8ea04a -r b56ee5853582 -r 918cf40a49c0 -r a65d60c840cb -r dc04fc0c66bd -r 8a4665601852 || exit
    fi
    cd mercurial-devel
    hg pull https://hg.sr.ht/~mjacob/hg-own -r 2fc7b6138a58 -r e7f9ada07e5f -r ca22543b6f9d -r 74825f8ea04a -r b56ee5853582 -r 918cf40a49c0 -r a65d60c840cb -r dc04fc0c66bd -r 8a4665601852

- script: |
    echo 'update to 2fc7b6138a58:'
    hg up -C 2fc7b6138a58
  workingDirectory: mercurial-devel
  displayName: Update to 2fc7b6138a58
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to e7f9ada07e5f:'
    hg up -C e7f9ada07e5f
  workingDirectory: mercurial-devel
  displayName: Update to e7f9ada07e5f
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to ca22543b6f9d:'
    hg up -C ca22543b6f9d
  workingDirectory: mercurial-devel
  displayName: Update to ca22543b6f9d
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 74825f8ea04a:'
    hg up -C 74825f8ea04a
  workingDirectory: mercurial-devel
  displayName: Update to 74825f8ea04a
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to b56ee5853582:'
    hg up -C b56ee5853582
  workingDirectory: mercurial-devel
  displayName: Update to b56ee5853582
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 918cf40a49c0:'
    hg up -C 918cf40a49c0
  workingDirectory: mercurial-devel
  displayName: Update to 918cf40a49c0
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to a65d60c840cb:'
    hg up -C a65d60c840cb
  workingDirectory: mercurial-devel
  displayName: Update to a65d60c840cb
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to dc04fc0c66bd:'
    hg up -C dc04fc0c66bd
  workingDirectory: mercurial-devel
  displayName: Update to dc04fc0c66bd
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 8a4665601852:'
    hg up -C 8a4665601852
  workingDirectory: mercurial-devel
  displayName: Update to 8a4665601852
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

