trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'

pool:
  vmImage: $(imageName)

steps:
- script: |
    $(python2) --version
    $(python3) --version
    pip install mercurial
    hg clone https://foss.heptapod.net/octobus/mercurial-devel -r cbec874a8b0f -r 527b213d2d24 -r e5036c93535d -r b0a51f31a3ae -r 7fb911423524 -r f330f7c409a9
    cd mercurial-devel

    hg up -C cbec874a8b0f
    echo 'at cbec874a8b0f:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

    hg up -C 527b213d2d24
    echo 'at 527b213d2d24:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

    hg up -C e5036c93535d
    echo 'at e5036c93535d:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

    hg up -C b0a51f31a3ae
    echo 'at b0a51f31a3ae:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

    hg up -C 7fb911423524
    echo 'at 7fb911423524:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

    hg up -C f330f7c409a9
    echo 'at f330f7c409a9:'
    $(python2) tests/test-stdio.py -v
    echo
    $(python3) tests/test-stdio.py -v
    echo
    echo

  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
