trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'

pool:
  vmImage: $(imageName)

steps:
- script: $(python2) --version
- script: $(python3) --version
- script: pip install mercurial
- script: hg clone https://foss.heptapod.net/octobus/mercurial-devel -r cfca4e64d577 -r 794874e83ec7 -r 0c7498610e47

- script: |
    echo 'update to cfca4e64d577:'
    hg up -C cfca4e64d577
  workingDirectory: mercurial-devel
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

- script: |
    echo 'update to 794874e83ec7:'
    hg up -C 794874e83ec7
  workingDirectory: mercurial-devel
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

- script: |
    echo 'update to 0c7498610e47:'
    hg up -C 0c7498610e47
  workingDirectory: mercurial-devel
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

