trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /home/vsts/.cache/pip
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /Users/runner/Library/Caches/pip
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'
      pip_cache_dir: C:\Users\VssAdministrator\AppData\Local\pip\cache

pool:
  vmImage: $(imageName)

steps:
- script: $(python2) --version
- script: $(python3) --version
- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)"'
    path: $(pip_cache_dir)
- script: pip install wheel
- script: pip install mercurial
- task: Cache@2
  inputs:
    key: 'hg | "$(Agent.OS)"'
    path: mercurial-devel
- bash: |
    if [ ! -d "mercurial-devel" ]; then
        hg clone https://hg.sr.ht/~mjacob/hg-own -r 88bd21f8b6ae -r 07c3a9cc1a8d -r 1fc294e28760 -r 478e7f8d0063 -r 776db0b6d5b6 -r 60d1bb947b8f || exit
    fi
    cd mercurial-devel
    hg pull https://hg.sr.ht/~mjacob/hg-own -r 88bd21f8b6ae -r 07c3a9cc1a8d -r 1fc294e28760 -r 478e7f8d0063 -r 776db0b6d5b6 -r 60d1bb947b8f

- script: |
    echo 'update to 88bd21f8b6ae:'
    hg up -C 88bd21f8b6ae
  workingDirectory: mercurial-devel
  displayName: Update to 88bd21f8b6ae
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 07c3a9cc1a8d:'
    hg up -C 07c3a9cc1a8d
  workingDirectory: mercurial-devel
  displayName: Update to 07c3a9cc1a8d
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 1fc294e28760:'
    hg up -C 1fc294e28760
  workingDirectory: mercurial-devel
  displayName: Update to 1fc294e28760
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 478e7f8d0063:'
    hg up -C 478e7f8d0063
  workingDirectory: mercurial-devel
  displayName: Update to 478e7f8d0063
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 776db0b6d5b6:'
    hg up -C 776db0b6d5b6
  workingDirectory: mercurial-devel
  displayName: Update to 776db0b6d5b6
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 60d1bb947b8f:'
    hg up -C 60d1bb947b8f
  workingDirectory: mercurial-devel
  displayName: Update to 60d1bb947b8f
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

