trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /home/vsts/.cache/pip
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /Users/runner/Library/Caches/pip
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'
      pip_cache_dir: C:\Users\VssAdministrator\AppData\Local\pip\cache

pool:
  vmImage: $(imageName)

steps:
- script: $(python2) --version
- script: $(python3) --version
- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)"'
    path: $(pip_cache_dir)
- script: pip install wheel
- script: pip install mercurial vcrpy
- task: Cache@2
  inputs:
    key: 'hg | "$(Agent.OS)"'
    path: mercurial-devel
- bash: |
    if [ ! -d "mercurial-devel" ]; then
        hg clone https://hg.sr.ht/~mjacob/hg-own -r 217660a6547c -r 90b4881b969c -r 91f6d0508aca -r 741837f16067 || exit
    fi
    cd mercurial-devel
    hg pull https://hg.sr.ht/~mjacob/hg-own -r 217660a6547c -r 90b4881b969c -r 91f6d0508aca -r 741837f16067

- script: |
    echo 'update to 217660a6547c:'
    hg up -C 217660a6547c
  workingDirectory: mercurial-devel
  displayName: Update to 217660a6547c
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python2) tests/run-tests.py --local tests/test-phabricator.t
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/run-tests.py --local tests/test-phabricator.t
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 90b4881b969c:'
    hg up -C 90b4881b969c
  workingDirectory: mercurial-devel
  displayName: Update to 90b4881b969c
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python2) tests/run-tests.py --local tests/test-phabricator.t
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/run-tests.py --local tests/test-phabricator.t
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 91f6d0508aca:'
    hg up -C 91f6d0508aca
  workingDirectory: mercurial-devel
  displayName: Update to 91f6d0508aca
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python2) tests/run-tests.py --local tests/test-phabricator.t
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/run-tests.py --local tests/test-phabricator.t
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 741837f16067:'
    hg up -C 741837f16067
  workingDirectory: mercurial-devel
  displayName: Update to 741837f16067
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python2) tests/run-tests.py --local tests/test-phabricator.t
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/run-tests.py --local tests/test-phabricator.t
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

