trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /home/vsts/.cache/pip
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /Users/runner/Library/Caches/pip
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'
      pip_cache_dir: C:\Users\VssAdministrator\AppData\Local\pip\cache

pool:
  vmImage: $(imageName)

steps:
- script: $(python2) --version
- script: $(python3) --version
- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)"'
    path: $(pip_cache_dir)
- script: pip install wheel
- script: pip install mercurial
- task: Cache@2
  inputs:
    key: 'hg | "$(Agent.OS)"'
    path: mercurial-devel
- bash: |
    if [ ! -d "mercurial-devel" ]; then
        hg clone https://hg.sr.ht/~mjacob/hg-own -r 2178c53039ac -r 271329a28ae2 -r 56b835bd7cb4 -r 7d5c94b54fe5 -r 6109510391c2 -r 2763cf96599d -r 556dfea068b9 || exit
    fi
    cd mercurial-devel
    hg pull -r 2178c53039ac -r 271329a28ae2 -r 56b835bd7cb4 -r 7d5c94b54fe5 -r 6109510391c2 -r 2763cf96599d -r 556dfea068b9

- script: |
    echo 'update to 2178c53039ac:'
    hg up -C 2178c53039ac
  workingDirectory: mercurial-devel
  displayName: Update to 2178c53039ac
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

- script: |
    echo 'update to 271329a28ae2:'
    hg up -C 271329a28ae2
  workingDirectory: mercurial-devel
  displayName: Update to 271329a28ae2
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

- script: |
    echo 'update to 56b835bd7cb4:'
    hg up -C 56b835bd7cb4
  workingDirectory: mercurial-devel
  displayName: Update to 56b835bd7cb4
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

- script: |
    echo 'update to 7d5c94b54fe5:'
    hg up -C 7d5c94b54fe5
  workingDirectory: mercurial-devel
  displayName: Update to 7d5c94b54fe5
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

- script: |
    echo 'update to 6109510391c2:'
    hg up -C 6109510391c2
  workingDirectory: mercurial-devel
  displayName: Update to 6109510391c2
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

- script: |
    echo 'update to 2763cf96599d:'
    hg up -C 2763cf96599d
  workingDirectory: mercurial-devel
  displayName: Update to 2763cf96599d
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

- script: |
    echo 'update to 556dfea068b9:'
    hg up -C 556dfea068b9
  workingDirectory: mercurial-devel
  displayName: Update to 556dfea068b9
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1

