trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /home/vsts/.cache/pip
    mac:
      imageName: 'macOS-10.15'
      python2: 'python2'
      python3: 'python3'
      pip_cache_dir: /Users/runner/Library/Caches/pip
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'
      pip_cache_dir: C:\Users\VssAdministrator\AppData\Local\pip\cache

pool:
  vmImage: $(imageName)

steps:
- script: $(python2) --version
- script: $(python3) --version
- task: Cache@2
  inputs:
    key: 'pip | "$(Agent.OS)"'
    path: $(pip_cache_dir)
- script: pip install wheel
- script: pip install mercurial
- task: Cache@2
  inputs:
    key: 'hg | "$(Agent.OS)"'
    path: mercurial-devel
- bash: |
    if [ ! -d "mercurial-devel" ]; then
        hg clone https://hg.sr.ht/~mjacob/hg-own -r 8718b4d5e08f -r 7e2a3c0ca7c5 || exit
    fi
    cd mercurial-devel
    hg pull https://hg.sr.ht/~mjacob/hg-own -r 8718b4d5e08f -r 7e2a3c0ca7c5

- script: |
    echo 'update to 8718b4d5e08f:'
    hg up -C 8718b4d5e08f
  workingDirectory: mercurial-devel
  displayName: Update to 8718b4d5e08f
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

- script: |
    echo 'update to 7e2a3c0ca7c5:'
    hg up -C 7e2a3c0ca7c5
  workingDirectory: mercurial-devel
  displayName: Update to 7e2a3c0ca7c5
- script: $(python2) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true
- script: $(python3) tests/test-stdio.py -v
  workingDirectory: mercurial-devel
  env:
    PYTHONPATH: .
    SILENT_BE_NOISY: 1
  timeoutInMinutes: 1
  continueOnError: true

